server:
  port: 8081

spring:
  application:
    name: ms-auth

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


access-refresh-token-path: "access-refresh-token-keys"

access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"

private_endpoints: /api/auth/val/** /ms/user/event/**