server:
  port: 8090

spring:
  application:
    name: ms-userevents
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/
      database: user-events-db

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka