server:
  port: 8090

spring:
  application:
    name: ms-userevents
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user-events-db
      username: admin
      password: password

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka