server:
  port: 8090

spring:
  application:
    name: ms-userevents
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/
      database: user-events-db
  kafka:
    bootstrap-servers: "localhost:29092"
    consumer:
      group-id: "user-events-group"

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka