server:
  port: 8090

spring:
  application:
    name: ms-userevents
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/
      database: user-events-db
    kafka:
      bootstrap-servers: "localhost:9092"
      consumer:
        group-id: "spring-user-events-group"

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka