server:
  port: '8092'

spring:
  application:
    name: ms-scheduler
  kafka:
    bootstrap-servers: "localhost:29092"
    consumer:
      group-id: "scheduler-group"

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka