server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-auth
          uri: 'http://localhost:8081'
          predicates:
            - Path=/api/auth/**
        - id: ms-userevent
          uri: 'http://localhost:8090'
          predicates:
            - Path=/ms/user/event/**
          filters:
            - AuthFilter

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
