server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-auth
          uri: 'http://localhost:8081'
          predicates:
            - Path=/api/auth/**
        - id: ms-example
          uri: 'http://localhost:9090'
          predicates:
            - Path=/example/test/**
          filters:
            - AuthFilter

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

feign:
  circuitbreaker:
    enabled: true


paths-bypass-auth-filer: /api/auth/**
