server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-auth
          uri: 'http://localhost:8081'
          predicates:
            - Path=/api/auth/**
        - id: students
          uri: 'http://localhost:8090'
          predicates:
            - Path=/api/student/**
        - id: courses
          uri: 'http://localhost:9090'
          predicates:
            - Path=/api/course/**

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


paths-bypass-auth-filer: /api/auth/**
